// Probar Annotation simple con ElementValuePairs vacio
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff
@Anotacion.aaaa.bbbb.ccc
@Anotacion.dddd.eee.ffffff

@Anotacion.gggg.hhhh.jjjjj package NombrePaquete;

import Java.asd.dfdfg.*;
import static dfgdf.dfgdf.ppp;

public class MiClase{}

private class ClasePrivada {}