/* Probar posibles valores de ElementValue
- ConditionalExpression
- Annotation
- ElementValueArrayInitializer
*/

// para conditionalExpression descomentar para probar
@AnotacionCondicional(23 + 45 * 5 )
// para Annotation descomentar para probar
@AnotacionAnotacion ( @asss.ddd( e = 34) )
// para elementValueArrayInitializer vacio package NombrePaquete;
@AnnotationelementaValueArrayIni( {})
// para elementValueArrayInitializer con elementos ElementValues
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})

@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})

@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
@AnotacionCondicional(23 + 45 * 5 )
@AnotacionAnotacion ( @asss.ddd( e = 34) )
@AnnotationelementaValueArrayIni( {})
@Annotation( {23+4, 4, {}, @www.wewe(a = 34)})
package NombrePaquete; 